version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=cartorio2023
      - POSTGRES_USER=usercartorio2023
      - POSTGRES_DB=cartorio